# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.executions_api import ExecutionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExecutionsApi(unittest.TestCase):
    """ExecutionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.executions_api.ExecutionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_execute(self):
        """Test case for execute

        Execute Task  # noqa: E501
        """
        pass

    def test_get_execution_status(self):
        """Test case for get_execution_status

        Get Task execution status  # noqa: E501
        """
        pass

    def test_stop_execution(self):
        """Test case for stop_execution

        Terminate Task execution  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
