# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.runtime__engines_api import RuntimeEnginesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRuntimeEnginesApi(unittest.TestCase):
    """RuntimeEnginesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.runtime__engines_api.RuntimeEnginesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_remote_engine(self):
        """Test case for create_remote_engine

        Create new Remote Engine  # noqa: E501
        """
        pass

    def test_delete_remote_engine(self):
        """Test case for delete_remote_engine

        Delete Remote Engine by id  # noqa: E501
        """
        pass

    def test_get_remote_engine(self):
        """Test case for get_remote_engine

        Get Remote Engine by id  # noqa: E501
        """
        pass

    def test_get_remote_engines(self):
        """Test case for get_remote_engines

        Get all (available) Remote Engines  # noqa: E501
        """
        pass

    def test_unpair_remote_engine(self):
        """Test case for unpair_remote_engine

        Unpair Remote Engine  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
