# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.plans__executables_api import PlansExecutablesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPlansExecutablesApi(unittest.TestCase):
    """PlansExecutablesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.plans__executables_api.PlansExecutablesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_configure_plan_execution(self):
        """Test case for configure_plan_execution

        Configure Plan execution  # noqa: E501
        """
        pass

    def test_create_plan(self):
        """Test case for create_plan

        Create Plan  # noqa: E501
        """
        pass

    def test_get_available_plans(self):
        """Test case for get_available_plans

        Get available Plans  # noqa: E501
        """
        pass

    def test_get_executable_details(self):
        """Test case for get_executable_details

        Get Plan details  # noqa: E501
        """
        pass

    def test_get_plan_configuration(self):
        """Test case for get_plan_configuration

        Get Plan configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
