# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.artifacts_api import ArtifactsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestArtifactsApi(unittest.TestCase):
    """ArtifactsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.artifacts_api.ArtifactsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_artifact(self):
        """Test case for get_artifact

        Get Artifact by id  # noqa: E501
        """
        pass

    def test_get_artifact_of_version(self):
        """Test case for get_artifact_of_version

        Get Artifact of a specified version  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
