# coding: utf-8

# flake8: noqa
"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.advanced_promotion_spec import AdvancedPromotionSpec
from swagger_client.models.artifact import Artifact
from swagger_client.models.artifact_parameter import ArtifactParameter
from swagger_client.models.artifact_request import ArtifactRequest
from swagger_client.models.artifact_version import ArtifactVersion
from swagger_client.models.base_artifact_version import BaseArtifactVersion
from swagger_client.models.base_engine import BaseEngine
from swagger_client.models.cluster_request import ClusterRequest
from swagger_client.models.day_schedule import DaySchedule
from swagger_client.models.engine import Engine
from swagger_client.models.engine_cluster import EngineCluster
from swagger_client.models.engine_debug import EngineDebug
from swagger_client.models.engine_request import EngineRequest
from swagger_client.models.environment_info import EnvironmentInfo
from swagger_client.models.error_response import ErrorResponse
from swagger_client.models.executable_task import ExecutableTask
from swagger_client.models.execution_flow import ExecutionFlow
from swagger_client.models.execution_identifier import ExecutionIdentifier
from swagger_client.models.execution_step import ExecutionStep
from swagger_client.models.job_execution_status import JobExecutionStatus
from swagger_client.models.message import Message
from swagger_client.models.page import Page
from swagger_client.models.plan import Plan
from swagger_client.models.plan_executable_details import PlanExecutableDetails
from swagger_client.models.plan_executable_task import PlanExecutableTask
from swagger_client.models.plan_execution_status import PlanExecutionStatus
from swagger_client.models.plan_request import PlanRequest
from swagger_client.models.promotion_artifact_execution_info import PromotionArtifactExecutionInfo
from swagger_client.models.promotion_executable_details import PromotionExecutableDetails
from swagger_client.models.promotion_executable_info import PromotionExecutableInfo
from swagger_client.models.promotion_executable_task import PromotionExecutableTask
from swagger_client.models.promotion_execution_info import PromotionExecutionInfo
from swagger_client.models.report import Report
from swagger_client.models.resource import Resource
from swagger_client.models.run_config import RunConfig
from swagger_client.models.run_connection import RunConnection
from swagger_client.models.runtime import Runtime
from swagger_client.models.step import Step
from swagger_client.models.step_error_handler import StepErrorHandler
from swagger_client.models.task import Task
from swagger_client.models.task_request import TaskRequest
from swagger_client.models.time_schedule import TimeSchedule
from swagger_client.models.trigger import Trigger
from swagger_client.models.webhook import Webhook
from swagger_client.models.workspace_info import WorkspaceInfo
from swagger_client.models.workspace_promotion_execution_info import WorkspacePromotionExecutionInfo
