# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ArtifactParameter(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'value': 'str',
        'type': 'str',
        'required': 'bool',
        'comment': 'str'
    }

    attribute_map = {
        'name': 'name',
        'value': 'value',
        'type': 'type',
        'required': 'required',
        'comment': 'comment'
    }

    def __init__(self, name=None, value=None, type=None, required=None, comment=None):  # noqa: E501
        """ArtifactParameter - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._value = None
        self._type = None
        self._required = None
        self._comment = None
        self.discriminator = None

        self.name = name
        if value is not None:
            self.value = value
        self.type = type
        self.required = required
        if comment is not None:
            self.comment = comment

    @property
    def name(self):
        """Gets the name of this ArtifactParameter.  # noqa: E501

        Parameter name  # noqa: E501

        :return: The name of this ArtifactParameter.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ArtifactParameter.

        Parameter name  # noqa: E501

        :param name: The name of this ArtifactParameter.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this ArtifactParameter.  # noqa: E501

        Parameter value  # noqa: E501

        :return: The value of this ArtifactParameter.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ArtifactParameter.

        Parameter value  # noqa: E501

        :param value: The value of this ArtifactParameter.  # noqa: E501
        :type: str
        """

        self._value = value

    @property
    def type(self):
        """Gets the type of this ArtifactParameter.  # noqa: E501

        Parameter value  # noqa: E501

        :return: The type of this ArtifactParameter.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ArtifactParameter.

        Parameter value  # noqa: E501

        :param type: The type of this ArtifactParameter.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def required(self):
        """Gets the required of this ArtifactParameter.  # noqa: E501

        Is parameter required or not  # noqa: E501

        :return: The required of this ArtifactParameter.  # noqa: E501
        :rtype: bool
        """
        return self._required

    @required.setter
    def required(self, required):
        """Sets the required of this ArtifactParameter.

        Is parameter required or not  # noqa: E501

        :param required: The required of this ArtifactParameter.  # noqa: E501
        :type: bool
        """
        if required is None:
            raise ValueError("Invalid value for `required`, must not be `None`")  # noqa: E501

        self._required = required

    @property
    def comment(self):
        """Gets the comment of this ArtifactParameter.  # noqa: E501

        Comment about parameter  # noqa: E501

        :return: The comment of this ArtifactParameter.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this ArtifactParameter.

        Comment about parameter  # noqa: E501

        :param comment: The comment of this ArtifactParameter.  # noqa: E501
        :type: str
        """

        self._comment = comment

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ArtifactParameter, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArtifactParameter):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
