# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExecutionFlow(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'version': 'str',
        'description': 'str',
        'destination': 'str',
        'workspace_id': 'str',
        'plan': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'version': 'version',
        'description': 'description',
        'destination': 'destination',
        'workspace_id': 'workspaceId',
        'plan': 'plan'
    }

    def __init__(self, id=None, name=None, version=None, description=None, destination=None, workspace_id=None, plan=None):  # noqa: E501
        """ExecutionFlow - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._version = None
        self._description = None
        self._destination = None
        self._workspace_id = None
        self._plan = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if version is not None:
            self.version = version
        if description is not None:
            self.description = description
        if destination is not None:
            self.destination = destination
        if workspace_id is not None:
            self.workspace_id = workspace_id
        if plan is not None:
            self.plan = plan

    @property
    def id(self):
        """Gets the id of this ExecutionFlow.  # noqa: E501


        :return: The id of this ExecutionFlow.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ExecutionFlow.


        :param id: The id of this ExecutionFlow.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this ExecutionFlow.  # noqa: E501


        :return: The name of this ExecutionFlow.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ExecutionFlow.


        :param name: The name of this ExecutionFlow.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def version(self):
        """Gets the version of this ExecutionFlow.  # noqa: E501


        :return: The version of this ExecutionFlow.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ExecutionFlow.


        :param version: The version of this ExecutionFlow.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def description(self):
        """Gets the description of this ExecutionFlow.  # noqa: E501


        :return: The description of this ExecutionFlow.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ExecutionFlow.


        :param description: The description of this ExecutionFlow.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def destination(self):
        """Gets the destination of this ExecutionFlow.  # noqa: E501


        :return: The destination of this ExecutionFlow.  # noqa: E501
        :rtype: str
        """
        return self._destination

    @destination.setter
    def destination(self, destination):
        """Sets the destination of this ExecutionFlow.


        :param destination: The destination of this ExecutionFlow.  # noqa: E501
        :type: str
        """

        self._destination = destination

    @property
    def workspace_id(self):
        """Gets the workspace_id of this ExecutionFlow.  # noqa: E501


        :return: The workspace_id of this ExecutionFlow.  # noqa: E501
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this ExecutionFlow.


        :param workspace_id: The workspace_id of this ExecutionFlow.  # noqa: E501
        :type: str
        """

        self._workspace_id = workspace_id

    @property
    def plan(self):
        """Gets the plan of this ExecutionFlow.  # noqa: E501


        :return: The plan of this ExecutionFlow.  # noqa: E501
        :rtype: bool
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this ExecutionFlow.


        :param plan: The plan of this ExecutionFlow.  # noqa: E501
        :type: bool
        """

        self._plan = plan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutionFlow, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionFlow):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
