# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExecutionStep(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'step_id': 'str',
        'step_name': 'str',
        'status': 'str',
        'step_on_exception': 'ExecutionStep',
        'next_step': 'ExecutionStep',
        'flows': 'list[ExecutionFlow]'
    }

    attribute_map = {
        'step_id': 'stepId',
        'step_name': 'stepName',
        'status': 'status',
        'step_on_exception': 'stepOnException',
        'next_step': 'nextStep',
        'flows': 'flows'
    }

    def __init__(self, step_id=None, step_name=None, status=None, step_on_exception=None, next_step=None, flows=None):  # noqa: E501
        """ExecutionStep - a model defined in Swagger"""  # noqa: E501

        self._step_id = None
        self._step_name = None
        self._status = None
        self._step_on_exception = None
        self._next_step = None
        self._flows = None
        self.discriminator = None

        if step_id is not None:
            self.step_id = step_id
        if step_name is not None:
            self.step_name = step_name
        if status is not None:
            self.status = status
        if step_on_exception is not None:
            self.step_on_exception = step_on_exception
        if next_step is not None:
            self.next_step = next_step
        if flows is not None:
            self.flows = flows

    @property
    def step_id(self):
        """Gets the step_id of this ExecutionStep.  # noqa: E501


        :return: The step_id of this ExecutionStep.  # noqa: E501
        :rtype: str
        """
        return self._step_id

    @step_id.setter
    def step_id(self, step_id):
        """Sets the step_id of this ExecutionStep.


        :param step_id: The step_id of this ExecutionStep.  # noqa: E501
        :type: str
        """

        self._step_id = step_id

    @property
    def step_name(self):
        """Gets the step_name of this ExecutionStep.  # noqa: E501


        :return: The step_name of this ExecutionStep.  # noqa: E501
        :rtype: str
        """
        return self._step_name

    @step_name.setter
    def step_name(self, step_name):
        """Sets the step_name of this ExecutionStep.


        :param step_name: The step_name of this ExecutionStep.  # noqa: E501
        :type: str
        """

        self._step_name = step_name

    @property
    def status(self):
        """Gets the status of this ExecutionStep.  # noqa: E501


        :return: The status of this ExecutionStep.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ExecutionStep.


        :param status: The status of this ExecutionStep.  # noqa: E501
        :type: str
        """
        allowed_values = ["SUCCESS", "PARTIAL_SUCCESS", "FAIL"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def step_on_exception(self):
        """Gets the step_on_exception of this ExecutionStep.  # noqa: E501


        :return: The step_on_exception of this ExecutionStep.  # noqa: E501
        :rtype: ExecutionStep
        """
        return self._step_on_exception

    @step_on_exception.setter
    def step_on_exception(self, step_on_exception):
        """Sets the step_on_exception of this ExecutionStep.


        :param step_on_exception: The step_on_exception of this ExecutionStep.  # noqa: E501
        :type: ExecutionStep
        """

        self._step_on_exception = step_on_exception

    @property
    def next_step(self):
        """Gets the next_step of this ExecutionStep.  # noqa: E501


        :return: The next_step of this ExecutionStep.  # noqa: E501
        :rtype: ExecutionStep
        """
        return self._next_step

    @next_step.setter
    def next_step(self, next_step):
        """Sets the next_step of this ExecutionStep.


        :param next_step: The next_step of this ExecutionStep.  # noqa: E501
        :type: ExecutionStep
        """

        self._next_step = next_step

    @property
    def flows(self):
        """Gets the flows of this ExecutionStep.  # noqa: E501


        :return: The flows of this ExecutionStep.  # noqa: E501
        :rtype: list[ExecutionFlow]
        """
        return self._flows

    @flows.setter
    def flows(self, flows):
        """Sets the flows of this ExecutionStep.


        :param flows: The flows of this ExecutionStep.  # noqa: E501
        :type: list[ExecutionFlow]
        """

        self._flows = flows

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutionStep, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionStep):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
