# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PromotionExecutableInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'source_environment': 'EnvironmentInfo',
        'target_environment': 'EnvironmentInfo',
        'executable': 'str',
        'name': 'str'
    }

    attribute_map = {
        'source_environment': 'sourceEnvironment',
        'target_environment': 'targetEnvironment',
        'executable': 'executable',
        'name': 'name'
    }

    def __init__(self, source_environment=None, target_environment=None, executable=None, name=None):  # noqa: E501
        """PromotionExecutableInfo - a model defined in Swagger"""  # noqa: E501

        self._source_environment = None
        self._target_environment = None
        self._executable = None
        self._name = None
        self.discriminator = None

        if source_environment is not None:
            self.source_environment = source_environment
        if target_environment is not None:
            self.target_environment = target_environment
        self.executable = executable
        self.name = name

    @property
    def source_environment(self):
        """Gets the source_environment of this PromotionExecutableInfo.  # noqa: E501

        Promotion Source Environment  # noqa: E501

        :return: The source_environment of this PromotionExecutableInfo.  # noqa: E501
        :rtype: EnvironmentInfo
        """
        return self._source_environment

    @source_environment.setter
    def source_environment(self, source_environment):
        """Sets the source_environment of this PromotionExecutableInfo.

        Promotion Source Environment  # noqa: E501

        :param source_environment: The source_environment of this PromotionExecutableInfo.  # noqa: E501
        :type: EnvironmentInfo
        """

        self._source_environment = source_environment

    @property
    def target_environment(self):
        """Gets the target_environment of this PromotionExecutableInfo.  # noqa: E501

        Promotion Target Environment  # noqa: E501

        :return: The target_environment of this PromotionExecutableInfo.  # noqa: E501
        :rtype: EnvironmentInfo
        """
        return self._target_environment

    @target_environment.setter
    def target_environment(self, target_environment):
        """Sets the target_environment of this PromotionExecutableInfo.

        Promotion Target Environment  # noqa: E501

        :param target_environment: The target_environment of this PromotionExecutableInfo.  # noqa: E501
        :type: EnvironmentInfo
        """

        self._target_environment = target_environment

    @property
    def executable(self):
        """Gets the executable of this PromotionExecutableInfo.  # noqa: E501

        Executable identifier  # noqa: E501

        :return: The executable of this PromotionExecutableInfo.  # noqa: E501
        :rtype: str
        """
        return self._executable

    @executable.setter
    def executable(self, executable):
        """Sets the executable of this PromotionExecutableInfo.

        Executable identifier  # noqa: E501

        :param executable: The executable of this PromotionExecutableInfo.  # noqa: E501
        :type: str
        """
        if executable is None:
            raise ValueError("Invalid value for `executable`, must not be `None`")  # noqa: E501

        self._executable = executable

    @property
    def name(self):
        """Gets the name of this PromotionExecutableInfo.  # noqa: E501

        Executable name  # noqa: E501

        :return: The name of this PromotionExecutableInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PromotionExecutableInfo.

        Executable name  # noqa: E501

        :param name: The name of this PromotionExecutableInfo.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PromotionExecutableInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PromotionExecutableInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
