# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class RuntimeClustersApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def add_remote_engine_to_cluster(self, cluster_id, engine_id, **kwargs):  # noqa: E501
        """Add Remote Engine to Remote Engine Cluster  # noqa: E501

        Add Remote Engine to Remote Engine Cluster  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_remote_engine_to_cluster(cluster_id, engine_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :param str engine_id: remote engine id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.add_remote_engine_to_cluster_with_http_info(cluster_id, engine_id, **kwargs)  # noqa: E501
        else:
            (data) = self.add_remote_engine_to_cluster_with_http_info(cluster_id, engine_id, **kwargs)  # noqa: E501
            return data

    def add_remote_engine_to_cluster_with_http_info(self, cluster_id, engine_id, **kwargs):  # noqa: E501
        """Add Remote Engine to Remote Engine Cluster  # noqa: E501

        Add Remote Engine to Remote Engine Cluster  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.add_remote_engine_to_cluster_with_http_info(cluster_id, engine_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :param str engine_id: remote engine id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cluster_id', 'engine_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method add_remote_engine_to_cluster" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'cluster_id' is set
        if ('cluster_id' not in params or
                params['cluster_id'] is None):
            raise ValueError("Missing the required parameter `cluster_id` when calling `add_remote_engine_to_cluster`")  # noqa: E501
        # verify the required parameter 'engine_id' is set
        if ('engine_id' not in params or
                params['engine_id'] is None):
            raise ValueError("Missing the required parameter `engine_id` when calling `add_remote_engine_to_cluster`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'cluster_id' in params:
            path_params['clusterId'] = params['cluster_id']  # noqa: E501
        if 'engine_id' in params:
            path_params['engineId'] = params['engine_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['Access Token', 'Basic Authentication']  # noqa: E501

        return self.api_client.call_api(
            '/runtimes/remote-engine-clusters/{clusterId}/engines/{engineId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_remote_engine_cluster(self, body, **kwargs):  # noqa: E501
        """Create Remote Engine Cluster  # noqa: E501

        Create Remote Engine Cluster  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_remote_engine_cluster(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ClusterRequest body: Remote Engine Cluster (required)
        :return: EngineCluster
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_remote_engine_cluster_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.create_remote_engine_cluster_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def create_remote_engine_cluster_with_http_info(self, body, **kwargs):  # noqa: E501
        """Create Remote Engine Cluster  # noqa: E501

        Create Remote Engine Cluster  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_remote_engine_cluster_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ClusterRequest body: Remote Engine Cluster (required)
        :return: EngineCluster
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_remote_engine_cluster" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `create_remote_engine_cluster`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Access Token', 'Basic Authentication']  # noqa: E501

        return self.api_client.call_api(
            '/runtimes/remote-engine-clusters', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EngineCluster',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_remote_engine_cluster(self, cluster_id, **kwargs):  # noqa: E501
        """Delete Remote Engine Cluster by id  # noqa: E501

        Delete Remote Engine Cluster by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_remote_engine_cluster(cluster_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_remote_engine_cluster_with_http_info(cluster_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_remote_engine_cluster_with_http_info(cluster_id, **kwargs)  # noqa: E501
            return data

    def delete_remote_engine_cluster_with_http_info(self, cluster_id, **kwargs):  # noqa: E501
        """Delete Remote Engine Cluster by id  # noqa: E501

        Delete Remote Engine Cluster by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_remote_engine_cluster_with_http_info(cluster_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cluster_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_remote_engine_cluster" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'cluster_id' is set
        if ('cluster_id' not in params or
                params['cluster_id'] is None):
            raise ValueError("Missing the required parameter `cluster_id` when calling `delete_remote_engine_cluster`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'cluster_id' in params:
            path_params['clusterId'] = params['cluster_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['Access Token', 'Basic Authentication']  # noqa: E501

        return self.api_client.call_api(
            '/runtimes/remote-engine-clusters/{clusterId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_engine_clusters_available(self, **kwargs):  # noqa: E501
        """Get all (available) Remote Engine Clusters  # noqa: E501

        Get all (available) Remote Engine Clusters  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_engine_clusters_available(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str s: search query (FIQL format), e.g. \"workspace.environment.id==5cb47ca4b1b5247f6006529e\",\"name==NewCluster\"
        :return: BaseEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_engine_clusters_available_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_engine_clusters_available_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_engine_clusters_available_with_http_info(self, **kwargs):  # noqa: E501
        """Get all (available) Remote Engine Clusters  # noqa: E501

        Get all (available) Remote Engine Clusters  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_engine_clusters_available_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str s: search query (FIQL format), e.g. \"workspace.environment.id==5cb47ca4b1b5247f6006529e\",\"name==NewCluster\"
        :return: BaseEngine
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['s']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_engine_clusters_available" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 's' in params:
            query_params.append(('_s', params['s']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Access Token', 'Basic Authentication']  # noqa: E501

        return self.api_client.call_api(
            '/runtimes/remote-engine-clusters', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BaseEngine',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_remote_engine_cluster(self, cluster_id, **kwargs):  # noqa: E501
        """Get Remote Engine Cluster by id  # noqa: E501

        Get Remote Engine Cluster by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_remote_engine_cluster(cluster_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :return: EngineCluster
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_remote_engine_cluster_with_http_info(cluster_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_remote_engine_cluster_with_http_info(cluster_id, **kwargs)  # noqa: E501
            return data

    def get_remote_engine_cluster_with_http_info(self, cluster_id, **kwargs):  # noqa: E501
        """Get Remote Engine Cluster by id  # noqa: E501

        Get Remote Engine Cluster by id  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_remote_engine_cluster_with_http_info(cluster_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :return: EngineCluster
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cluster_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_remote_engine_cluster" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'cluster_id' is set
        if ('cluster_id' not in params or
                params['cluster_id'] is None):
            raise ValueError("Missing the required parameter `cluster_id` when calling `get_remote_engine_cluster`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'cluster_id' in params:
            path_params['clusterId'] = params['cluster_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Access Token', 'Basic Authentication']  # noqa: E501

        return self.api_client.call_api(
            '/runtimes/remote-engine-clusters/{clusterId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='EngineCluster',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def remove_remote_engine_from_cluster(self, cluster_id, engine_id, **kwargs):  # noqa: E501
        """Remove Remote Engine from Remote Engine Cluster  # noqa: E501

        Remove Remote Engine from Remote Engine Cluster  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_remote_engine_from_cluster(cluster_id, engine_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :param str engine_id: remote engine id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.remove_remote_engine_from_cluster_with_http_info(cluster_id, engine_id, **kwargs)  # noqa: E501
        else:
            (data) = self.remove_remote_engine_from_cluster_with_http_info(cluster_id, engine_id, **kwargs)  # noqa: E501
            return data

    def remove_remote_engine_from_cluster_with_http_info(self, cluster_id, engine_id, **kwargs):  # noqa: E501
        """Remove Remote Engine from Remote Engine Cluster  # noqa: E501

        Remove Remote Engine from Remote Engine Cluster  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.remove_remote_engine_from_cluster_with_http_info(cluster_id, engine_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str cluster_id: remote engine cluster id (required)
        :param str engine_id: remote engine id (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['cluster_id', 'engine_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method remove_remote_engine_from_cluster" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'cluster_id' is set
        if ('cluster_id' not in params or
                params['cluster_id'] is None):
            raise ValueError("Missing the required parameter `cluster_id` when calling `remove_remote_engine_from_cluster`")  # noqa: E501
        # verify the required parameter 'engine_id' is set
        if ('engine_id' not in params or
                params['engine_id'] is None):
            raise ValueError("Missing the required parameter `engine_id` when calling `remove_remote_engine_from_cluster`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'cluster_id' in params:
            path_params['clusterId'] = params['cluster_id']  # noqa: E501
        if 'engine_id' in params:
            path_params['engineId'] = params['engine_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Access Token', 'Basic Authentication']  # noqa: E501

        return self.api_client.call_api(
            '/runtimes/remote-engine-clusters/{clusterId}/engines/{engineId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
