# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.promotions__executions_api import PromotionsExecutionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPromotionsExecutionsApi(unittest.TestCase):
    """PromotionsExecutionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.promotions__executions_api.PromotionsExecutionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_execute(self):
        """Test case for execute

        Execute Promotion  # noqa: E501
        """
        pass

    def test_get_execution_status(self):
        """Test case for get_execution_status

        Get Promotion execution status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
