# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.configuration_api import ConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestConfigurationApi(unittest.TestCase):
    """ConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.configuration_api.ConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_connection(self):
        """Test case for get_connection

        Get Connection by id  # noqa: E501
        """
        pass

    def test_get_resource(self):
        """Test case for get_resource

        Get Resource by id  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
