# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.promotions__executables_api import PromotionsExecutablesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPromotionsExecutablesApi(unittest.TestCase):
    """PromotionsExecutablesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.promotions__executables_api.PromotionsExecutablesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_executable_details(self):
        """Test case for get_executable_details

        Get Promotion details  # noqa: E501
        """
        pass

    def test_get_executables_available(self):
        """Test case for get_executables_available

        Get available Promotions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
