# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.runtime__clusters_api import RuntimeClustersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRuntimeClustersApi(unittest.TestCase):
    """RuntimeClustersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.runtime__clusters_api.RuntimeClustersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_remote_engine_to_cluster(self):
        """Test case for add_remote_engine_to_cluster

        Add Remote Engine to Remote Engine Cluster  # noqa: E501
        """
        pass

    def test_create_remote_engine_cluster(self):
        """Test case for create_remote_engine_cluster

        Create Remote Engine Cluster  # noqa: E501
        """
        pass

    def test_delete_remote_engine_cluster(self):
        """Test case for delete_remote_engine_cluster

        Delete Remote Engine Cluster by id  # noqa: E501
        """
        pass

    def test_get_engine_clusters_available(self):
        """Test case for get_engine_clusters_available

        Get all (available) Remote Engine Clusters  # noqa: E501
        """
        pass

    def test_get_remote_engine_cluster(self):
        """Test case for get_remote_engine_cluster

        Get Remote Engine Cluster by id  # noqa: E501
        """
        pass

    def test_remove_remote_engine_from_cluster(self):
        """Test case for remove_remote_engine_from_cluster

        Remove Remote Engine from Remote Engine Cluster  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
