# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ArtifactVersion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'version': 'str',
        'type': 'str',
        'publisher': 'str',
        'marketplace_product': 'str',
        'parameters': 'list[ArtifactParameter]',
        'workspace': 'WorkspaceInfo',
        'description': 'str',
        'create_date': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'version': 'version',
        'type': 'type',
        'publisher': 'publisher',
        'marketplace_product': 'marketplaceProduct',
        'parameters': 'parameters',
        'workspace': 'workspace',
        'description': 'description',
        'create_date': 'createDate'
    }

    def __init__(self, id=None, name=None, version=None, type=None, publisher=None, marketplace_product=None, parameters=None, workspace=None, description=None, create_date=None):  # noqa: E501
        """ArtifactVersion - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._version = None
        self._type = None
        self._publisher = None
        self._marketplace_product = None
        self._parameters = None
        self._workspace = None
        self._description = None
        self._create_date = None
        self.discriminator = None

        self.id = id
        if name is not None:
            self.name = name
        self.version = version
        self.type = type
        self.publisher = publisher
        self.marketplace_product = marketplace_product
        self.parameters = parameters
        self.workspace = workspace
        if description is not None:
            self.description = description
        self.create_date = create_date

    @property
    def id(self):
        """Gets the id of this ArtifactVersion.  # noqa: E501

        Id of artifact  # noqa: E501

        :return: The id of this ArtifactVersion.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ArtifactVersion.

        Id of artifact  # noqa: E501

        :param id: The id of this ArtifactVersion.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ArtifactVersion.  # noqa: E501

        Name of artifact  # noqa: E501

        :return: The name of this ArtifactVersion.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ArtifactVersion.

        Name of artifact  # noqa: E501

        :param name: The name of this ArtifactVersion.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def version(self):
        """Gets the version of this ArtifactVersion.  # noqa: E501

        Artifact version  # noqa: E501

        :return: The version of this ArtifactVersion.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this ArtifactVersion.

        Artifact version  # noqa: E501

        :param version: The version of this ArtifactVersion.  # noqa: E501
        :type: str
        """
        if version is None:
            raise ValueError("Invalid value for `version`, must not be `None`")  # noqa: E501

        self._version = version

    @property
    def type(self):
        """Gets the type of this ArtifactVersion.  # noqa: E501

        Artifact type  # noqa: E501

        :return: The type of this ArtifactVersion.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ArtifactVersion.

        Artifact type  # noqa: E501

        :param type: The type of this ArtifactVersion.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["standard", "big_data_streaming", "big_data_batch", "route", "data-service"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def publisher(self):
        """Gets the publisher of this ArtifactVersion.  # noqa: E501

        Artifact publisher  # noqa: E501

        :return: The publisher of this ArtifactVersion.  # noqa: E501
        :rtype: str
        """
        return self._publisher

    @publisher.setter
    def publisher(self, publisher):
        """Sets the publisher of this ArtifactVersion.

        Artifact publisher  # noqa: E501

        :param publisher: The publisher of this ArtifactVersion.  # noqa: E501
        :type: str
        """
        if publisher is None:
            raise ValueError("Invalid value for `publisher`, must not be `None`")  # noqa: E501

        self._publisher = publisher

    @property
    def marketplace_product(self):
        """Gets the marketplace_product of this ArtifactVersion.  # noqa: E501

        Marketplace product  # noqa: E501

        :return: The marketplace_product of this ArtifactVersion.  # noqa: E501
        :rtype: str
        """
        return self._marketplace_product

    @marketplace_product.setter
    def marketplace_product(self, marketplace_product):
        """Sets the marketplace_product of this ArtifactVersion.

        Marketplace product  # noqa: E501

        :param marketplace_product: The marketplace_product of this ArtifactVersion.  # noqa: E501
        :type: str
        """
        if marketplace_product is None:
            raise ValueError("Invalid value for `marketplace_product`, must not be `None`")  # noqa: E501

        self._marketplace_product = marketplace_product

    @property
    def parameters(self):
        """Gets the parameters of this ArtifactVersion.  # noqa: E501

        Artifact parameters  # noqa: E501

        :return: The parameters of this ArtifactVersion.  # noqa: E501
        :rtype: list[ArtifactParameter]
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this ArtifactVersion.

        Artifact parameters  # noqa: E501

        :param parameters: The parameters of this ArtifactVersion.  # noqa: E501
        :type: list[ArtifactParameter]
        """
        if parameters is None:
            raise ValueError("Invalid value for `parameters`, must not be `None`")  # noqa: E501

        self._parameters = parameters

    @property
    def workspace(self):
        """Gets the workspace of this ArtifactVersion.  # noqa: E501

        Artifact workspace  # noqa: E501

        :return: The workspace of this ArtifactVersion.  # noqa: E501
        :rtype: WorkspaceInfo
        """
        return self._workspace

    @workspace.setter
    def workspace(self, workspace):
        """Sets the workspace of this ArtifactVersion.

        Artifact workspace  # noqa: E501

        :param workspace: The workspace of this ArtifactVersion.  # noqa: E501
        :type: WorkspaceInfo
        """
        if workspace is None:
            raise ValueError("Invalid value for `workspace`, must not be `None`")  # noqa: E501

        self._workspace = workspace

    @property
    def description(self):
        """Gets the description of this ArtifactVersion.  # noqa: E501

        Artifact description  # noqa: E501

        :return: The description of this ArtifactVersion.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this ArtifactVersion.

        Artifact description  # noqa: E501

        :param description: The description of this ArtifactVersion.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def create_date(self):
        """Gets the create_date of this ArtifactVersion.  # noqa: E501

        Artifact date of creation  # noqa: E501

        :return: The create_date of this ArtifactVersion.  # noqa: E501
        :rtype: datetime
        """
        return self._create_date

    @create_date.setter
    def create_date(self, create_date):
        """Sets the create_date of this ArtifactVersion.

        Artifact date of creation  # noqa: E501

        :param create_date: The create_date of this ArtifactVersion.  # noqa: E501
        :type: datetime
        """
        if create_date is None:
            raise ValueError("Invalid value for `create_date`, must not be `None`")  # noqa: E501

        self._create_date = create_date

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ArtifactVersion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArtifactVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
