# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Artifact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'versions': 'list[str]',
        'workspace': 'WorkspaceInfo'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'versions': 'versions',
        'workspace': 'workspace'
    }

    def __init__(self, id=None, name=None, type=None, versions=None, workspace=None):  # noqa: E501
        """Artifact - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._type = None
        self._versions = None
        self._workspace = None
        self.discriminator = None

        self.id = id
        self.name = name
        self.type = type
        self.versions = versions
        self.workspace = workspace

    @property
    def id(self):
        """Gets the id of this Artifact.  # noqa: E501

        Artifact identifier  # noqa: E501

        :return: The id of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Artifact.

        Artifact identifier  # noqa: E501

        :param id: The id of this Artifact.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Artifact.  # noqa: E501

        Artifact name  # noqa: E501

        :return: The name of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Artifact.

        Artifact name  # noqa: E501

        :param name: The name of this Artifact.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this Artifact.  # noqa: E501

        Artifact type  # noqa: E501

        :return: The type of this Artifact.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Artifact.

        Artifact type  # noqa: E501

        :param type: The type of this Artifact.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
        allowed_values = ["standard", "big_data_streaming", "big_data_batch", "route", "data-service"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def versions(self):
        """Gets the versions of this Artifact.  # noqa: E501

        Available artifact versions  # noqa: E501

        :return: The versions of this Artifact.  # noqa: E501
        :rtype: list[str]
        """
        return self._versions

    @versions.setter
    def versions(self, versions):
        """Sets the versions of this Artifact.

        Available artifact versions  # noqa: E501

        :param versions: The versions of this Artifact.  # noqa: E501
        :type: list[str]
        """
        if versions is None:
            raise ValueError("Invalid value for `versions`, must not be `None`")  # noqa: E501

        self._versions = versions

    @property
    def workspace(self):
        """Gets the workspace of this Artifact.  # noqa: E501

        Artifact workspace  # noqa: E501

        :return: The workspace of this Artifact.  # noqa: E501
        :rtype: WorkspaceInfo
        """
        return self._workspace

    @workspace.setter
    def workspace(self, workspace):
        """Sets the workspace of this Artifact.

        Artifact workspace  # noqa: E501

        :param workspace: The workspace of this Artifact.  # noqa: E501
        :type: WorkspaceInfo
        """
        if workspace is None:
            raise ValueError("Invalid value for `workspace`, must not be `None`")  # noqa: E501

        self._workspace = workspace

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Artifact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Artifact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
