# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EngineRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'environment_id': 'str',
        'workspace_id': 'str',
        'run_profiles': 'list[str]',
        'debug': 'EngineDebug',
        'description': 'str'
    }

    attribute_map = {
        'name': 'name',
        'environment_id': 'environmentId',
        'workspace_id': 'workspaceId',
        'run_profiles': 'runProfiles',
        'debug': 'debug',
        'description': 'description'
    }

    def __init__(self, name=None, environment_id=None, workspace_id=None, run_profiles=None, debug=None, description=None):  # noqa: E501
        """EngineRequest - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._environment_id = None
        self._workspace_id = None
        self._run_profiles = None
        self._debug = None
        self._description = None
        self.discriminator = None

        self.name = name
        self.environment_id = environment_id
        if workspace_id is not None:
            self.workspace_id = workspace_id
        if run_profiles is not None:
            self.run_profiles = run_profiles
        if debug is not None:
            self.debug = debug
        if description is not None:
            self.description = description

    @property
    def name(self):
        """Gets the name of this EngineRequest.  # noqa: E501

        Engine name  # noqa: E501

        :return: The name of this EngineRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EngineRequest.

        Engine name  # noqa: E501

        :param name: The name of this EngineRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def environment_id(self):
        """Gets the environment_id of this EngineRequest.  # noqa: E501

        Id of engine environment  # noqa: E501

        :return: The environment_id of this EngineRequest.  # noqa: E501
        :rtype: str
        """
        return self._environment_id

    @environment_id.setter
    def environment_id(self, environment_id):
        """Sets the environment_id of this EngineRequest.

        Id of engine environment  # noqa: E501

        :param environment_id: The environment_id of this EngineRequest.  # noqa: E501
        :type: str
        """
        if environment_id is None:
            raise ValueError("Invalid value for `environment_id`, must not be `None`")  # noqa: E501

        self._environment_id = environment_id

    @property
    def workspace_id(self):
        """Gets the workspace_id of this EngineRequest.  # noqa: E501

        Id of engine workspace  # noqa: E501

        :return: The workspace_id of this EngineRequest.  # noqa: E501
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this EngineRequest.

        Id of engine workspace  # noqa: E501

        :param workspace_id: The workspace_id of this EngineRequest.  # noqa: E501
        :type: str
        """

        self._workspace_id = workspace_id

    @property
    def run_profiles(self):
        """Gets the run_profiles of this EngineRequest.  # noqa: E501

        Run profiles of engine  # noqa: E501

        :return: The run_profiles of this EngineRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._run_profiles

    @run_profiles.setter
    def run_profiles(self, run_profiles):
        """Sets the run_profiles of this EngineRequest.

        Run profiles of engine  # noqa: E501

        :param run_profiles: The run_profiles of this EngineRequest.  # noqa: E501
        :type: list[str]
        """

        self._run_profiles = run_profiles

    @property
    def debug(self):
        """Gets the debug of this EngineRequest.  # noqa: E501

        Remote Run/Debug configuration  # noqa: E501

        :return: The debug of this EngineRequest.  # noqa: E501
        :rtype: EngineDebug
        """
        return self._debug

    @debug.setter
    def debug(self, debug):
        """Sets the debug of this EngineRequest.

        Remote Run/Debug configuration  # noqa: E501

        :param debug: The debug of this EngineRequest.  # noqa: E501
        :type: EngineDebug
        """

        self._debug = debug

    @property
    def description(self):
        """Gets the description of this EngineRequest.  # noqa: E501

        Engine|cluster description  # noqa: E501

        :return: The description of this EngineRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this EngineRequest.

        Engine|cluster description  # noqa: E501

        :param description: The description of this EngineRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EngineRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EngineRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
