# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ErrorResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'int',
        'message': 'str',
        'details': 'str',
        'code': 'str',
        'url': 'str',
        'request_id': 'str'
    }

    attribute_map = {
        'status': 'status',
        'message': 'message',
        'details': 'details',
        'code': 'code',
        'url': 'url',
        'request_id': 'requestId'
    }

    def __init__(self, status=None, message=None, details=None, code=None, url=None, request_id=None):  # noqa: E501
        """ErrorResponse - a model defined in Swagger"""  # noqa: E501

        self._status = None
        self._message = None
        self._details = None
        self._code = None
        self._url = None
        self._request_id = None
        self.discriminator = None

        self.status = status
        self.message = message
        if details is not None:
            self.details = details
        if code is not None:
            self.code = code
        if url is not None:
            self.url = url
        self.request_id = request_id

    @property
    def status(self):
        """Gets the status of this ErrorResponse.  # noqa: E501

        Status code  # noqa: E501

        :return: The status of this ErrorResponse.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ErrorResponse.

        Status code  # noqa: E501

        :param status: The status of this ErrorResponse.  # noqa: E501
        :type: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def message(self):
        """Gets the message of this ErrorResponse.  # noqa: E501

        Error message (multilanguage). Info about error for user.  # noqa: E501

        :return: The message of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this ErrorResponse.

        Error message (multilanguage). Info about error for user.  # noqa: E501

        :param message: The message of this ErrorResponse.  # noqa: E501
        :type: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message

    @property
    def details(self):
        """Gets the details of this ErrorResponse.  # noqa: E501

        Developer message (not translated). Info about error for developer.  # noqa: E501

        :return: The details of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._details

    @details.setter
    def details(self, details):
        """Sets the details of this ErrorResponse.

        Developer message (not translated). Info about error for developer.  # noqa: E501

        :param details: The details of this ErrorResponse.  # noqa: E501
        :type: str
        """

        self._details = details

    @property
    def code(self):
        """Gets the code of this ErrorResponse.  # noqa: E501

        Internal error code  # noqa: E501

        :return: The code of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this ErrorResponse.

        Internal error code  # noqa: E501

        :param code: The code of this ErrorResponse.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def url(self):
        """Gets the url of this ErrorResponse.  # noqa: E501

        URL provided detailed info about error  # noqa: E501

        :return: The url of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this ErrorResponse.

        URL provided detailed info about error  # noqa: E501

        :param url: The url of this ErrorResponse.  # noqa: E501
        :type: str
        """

        self._url = url

    @property
    def request_id(self):
        """Gets the request_id of this ErrorResponse.  # noqa: E501

        The unique identification of the request involved with this error  # noqa: E501

        :return: The request_id of this ErrorResponse.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this ErrorResponse.

        The unique identification of the request involved with this error  # noqa: E501

        :param request_id: The request_id of this ErrorResponse.  # noqa: E501
        :type: str
        """
        if request_id is None:
            raise ValueError("Invalid value for `request_id`, must not be `None`")  # noqa: E501

        self._request_id = request_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ErrorResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ErrorResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
