# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ExecutableTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'executable': 'str',
        'parameters': 'dict(str, str)'
    }

    attribute_map = {
        'executable': 'executable',
        'parameters': 'parameters'
    }

    def __init__(self, executable=None, parameters=None):  # noqa: E501
        """ExecutableTask - a model defined in Swagger"""  # noqa: E501

        self._executable = None
        self._parameters = None
        self.discriminator = None

        self.executable = executable
        if parameters is not None:
            self.parameters = parameters

    @property
    def executable(self):
        """Gets the executable of this ExecutableTask.  # noqa: E501

        Executable identifier  # noqa: E501

        :return: The executable of this ExecutableTask.  # noqa: E501
        :rtype: str
        """
        return self._executable

    @executable.setter
    def executable(self, executable):
        """Sets the executable of this ExecutableTask.

        Executable identifier  # noqa: E501

        :param executable: The executable of this ExecutableTask.  # noqa: E501
        :type: str
        """
        if executable is None:
            raise ValueError("Invalid value for `executable`, must not be `None`")  # noqa: E501

        self._executable = executable

    @property
    def parameters(self):
        """Gets the parameters of this ExecutableTask.  # noqa: E501

        Executable parameters  # noqa: E501

        :return: The parameters of this ExecutableTask.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._parameters

    @parameters.setter
    def parameters(self, parameters):
        """Sets the parameters of this ExecutableTask.

        Executable parameters  # noqa: E501

        :param parameters: The parameters of this ExecutableTask.  # noqa: E501
        :type: dict(str, str)
        """

        self._parameters = parameters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutableTask, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutableTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
