# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PlanRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'workspace_id': 'str',
        'description': 'str',
        'steps': 'list[Step]'
    }

    attribute_map = {
        'name': 'name',
        'workspace_id': 'workspaceId',
        'description': 'description',
        'steps': 'steps'
    }

    def __init__(self, name=None, workspace_id=None, description=None, steps=None):  # noqa: E501
        """PlanRequest - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._workspace_id = None
        self._description = None
        self._steps = None
        self.discriminator = None

        self.name = name
        self.workspace_id = workspace_id
        if description is not None:
            self.description = description
        self.steps = steps

    @property
    def name(self):
        """Gets the name of this PlanRequest.  # noqa: E501

        Plan name  # noqa: E501

        :return: The name of this PlanRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PlanRequest.

        Plan name  # noqa: E501

        :param name: The name of this PlanRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def workspace_id(self):
        """Gets the workspace_id of this PlanRequest.  # noqa: E501

        Plan workspace  # noqa: E501

        :return: The workspace_id of this PlanRequest.  # noqa: E501
        :rtype: str
        """
        return self._workspace_id

    @workspace_id.setter
    def workspace_id(self, workspace_id):
        """Sets the workspace_id of this PlanRequest.

        Plan workspace  # noqa: E501

        :param workspace_id: The workspace_id of this PlanRequest.  # noqa: E501
        :type: str
        """
        if workspace_id is None:
            raise ValueError("Invalid value for `workspace_id`, must not be `None`")  # noqa: E501

        self._workspace_id = workspace_id

    @property
    def description(self):
        """Gets the description of this PlanRequest.  # noqa: E501

        Plan description  # noqa: E501

        :return: The description of this PlanRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PlanRequest.

        Plan description  # noqa: E501

        :param description: The description of this PlanRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def steps(self):
        """Gets the steps of this PlanRequest.  # noqa: E501

        Plan steps  # noqa: E501

        :return: The steps of this PlanRequest.  # noqa: E501
        :rtype: list[Step]
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this PlanRequest.

        Plan steps  # noqa: E501

        :param steps: The steps of this PlanRequest.  # noqa: E501
        :type: list[Step]
        """
        if steps is None:
            raise ValueError("Invalid value for `steps`, must not be `None`")  # noqa: E501

        self._steps = steps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PlanRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PlanRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
