# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Resource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'description': 'str',
        'workspace_info': 'WorkspaceInfo',
        'file': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'description': 'description',
        'workspace_info': 'workspaceInfo',
        'file': 'file'
    }

    def __init__(self, id=None, name=None, description=None, workspace_info=None, file=None):  # noqa: E501
        """Resource - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._description = None
        self._workspace_info = None
        self._file = None
        self.discriminator = None

        self.id = id
        self.name = name
        if description is not None:
            self.description = description
        self.workspace_info = workspace_info
        self.file = file

    @property
    def id(self):
        """Gets the id of this Resource.  # noqa: E501

        Id of resource  # noqa: E501

        :return: The id of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Resource.

        Id of resource  # noqa: E501

        :param id: The id of this Resource.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Resource.  # noqa: E501

        Name of resource  # noqa: E501

        :return: The name of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Resource.

        Name of resource  # noqa: E501

        :param name: The name of this Resource.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this Resource.  # noqa: E501

        Description of resource  # noqa: E501

        :return: The description of this Resource.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Resource.

        Description of resource  # noqa: E501

        :param description: The description of this Resource.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def workspace_info(self):
        """Gets the workspace_info of this Resource.  # noqa: E501

        Workspace of resource  # noqa: E501

        :return: The workspace_info of this Resource.  # noqa: E501
        :rtype: WorkspaceInfo
        """
        return self._workspace_info

    @workspace_info.setter
    def workspace_info(self, workspace_info):
        """Sets the workspace_info of this Resource.

        Workspace of resource  # noqa: E501

        :param workspace_info: The workspace_info of this Resource.  # noqa: E501
        :type: WorkspaceInfo
        """
        if workspace_info is None:
            raise ValueError("Invalid value for `workspace_info`, must not be `None`")  # noqa: E501

        self._workspace_info = workspace_info

    @property
    def file(self):
        """Gets the file of this Resource.  # noqa: E501

        Boolean value which indicates that resource is file  # noqa: E501

        :return: The file of this Resource.  # noqa: E501
        :rtype: bool
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this Resource.

        Boolean value which indicates that resource is file  # noqa: E501

        :param file: The file of this Resource.  # noqa: E501
        :type: bool
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Resource, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Resource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
