# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Runtime(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'id': 'str',
        'run_profile_id': 'str'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'run_profile_id': 'runProfileId'
    }

    def __init__(self, type=None, id=None, run_profile_id=None):  # noqa: E501
        """Runtime - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._id = None
        self._run_profile_id = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if id is not None:
            self.id = id
        if run_profile_id is not None:
            self.run_profile_id = run_profile_id

    @property
    def type(self):
        """Gets the type of this Runtime.  # noqa: E501

        Type of runtime  # noqa: E501

        :return: The type of this Runtime.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Runtime.

        Type of runtime  # noqa: E501

        :param type: The type of this Runtime.  # noqa: E501
        :type: str
        """
        allowed_values = ["CLOUD", "REMOTE_ENGINE", "REMOTE_ENGINE_CLUSTER", "CLOUD_EXCLUSIVE"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def id(self):
        """Gets the id of this Runtime.  # noqa: E501

        Runtime id  # noqa: E501

        :return: The id of this Runtime.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Runtime.

        Runtime id  # noqa: E501

        :param id: The id of this Runtime.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def run_profile_id(self):
        """Gets the run_profile_id of this Runtime.  # noqa: E501

        Run profile id  # noqa: E501

        :return: The run_profile_id of this Runtime.  # noqa: E501
        :rtype: str
        """
        return self._run_profile_id

    @run_profile_id.setter
    def run_profile_id(self, run_profile_id):
        """Sets the run_profile_id of this Runtime.

        Run profile id  # noqa: E501

        :param run_profile_id: The run_profile_id of this Runtime.  # noqa: E501
        :type: str
        """

        self._run_profile_id = run_profile_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Runtime, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Runtime):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
