# coding: utf-8

"""
    Talend Management Console Public API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class StepErrorHandler(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'task_ids': 'list[str]',
        'plan_ids': 'list[str]'
    }

    attribute_map = {
        'task_ids': 'taskIds',
        'plan_ids': 'planIds'
    }

    def __init__(self, task_ids=None, plan_ids=None):  # noqa: E501
        """StepErrorHandler - a model defined in Swagger"""  # noqa: E501

        self._task_ids = None
        self._plan_ids = None
        self.discriminator = None

        if task_ids is not None:
            self.task_ids = task_ids
        if plan_ids is not None:
            self.plan_ids = plan_ids

    @property
    def task_ids(self):
        """Gets the task_ids of this StepErrorHandler.  # noqa: E501

        List of handler tasks  # noqa: E501

        :return: The task_ids of this StepErrorHandler.  # noqa: E501
        :rtype: list[str]
        """
        return self._task_ids

    @task_ids.setter
    def task_ids(self, task_ids):
        """Sets the task_ids of this StepErrorHandler.

        List of handler tasks  # noqa: E501

        :param task_ids: The task_ids of this StepErrorHandler.  # noqa: E501
        :type: list[str]
        """

        self._task_ids = task_ids

    @property
    def plan_ids(self):
        """Gets the plan_ids of this StepErrorHandler.  # noqa: E501

        List of handler plans  # noqa: E501

        :return: The plan_ids of this StepErrorHandler.  # noqa: E501
        :rtype: list[str]
        """
        return self._plan_ids

    @plan_ids.setter
    def plan_ids(self, plan_ids):
        """Sets the plan_ids of this StepErrorHandler.

        List of handler plans  # noqa: E501

        :param plan_ids: The plan_ids of this StepErrorHandler.  # noqa: E501
        :type: list[str]
        """

        self._plan_ids = plan_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StepErrorHandler, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StepErrorHandler):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
